DROP TABLE IF EXISTS CUSTOMERS;

CREATE TABLE CUSTOMERS (
  id INT AUTO_INCREMENT  PRIMARY KEY,
  name VARCHAR(45) NOT NULL,
  surname VARCHAR(45) NOT NULL,
  age VARCHAR(3) DEFAULT NULL
);

INSERT INTO CUSTOMERS VALUES (1, 'MARIAN', 'BRODA', '29');
INSERT INTO CUSTOMERS VALUES (2, 'JOLA', 'PUPCIA', '27');

DROP TABLE IF EXISTS CONTACTS;

CREATE TABLE CONTACTS (
    id INT AUTO_INCREMENT  PRIMARY KEY,
    id_customer INT unique REFERENCES CUSTOMERS(id),
    type INT NOT NULL,
    contact VARCHAR(50)
);

INSERT INTO CONTACTS VALUES (1, 1, 1, 'marianbroda@dupa.pl');
INSERT INTO CONTACTS VALUES (2, 2, 1, 'andrzejdupa@dupa.pl');
