DROP TABLE IF EXISTS CUSTOMERS;

CREATE TABLE CUSTOMERS (
  id INT AUTO_INCREMENT  PRIMARY KEY,
  name VARCHAR(45) NOT NULL,
  surname VARCHAR(45) NOT NULL,
  age VARCHAR(3) DEFAULT NULL
);

INSERT INTO CUSTOMERS VALUES (1, 'MARIAN', 'BRODA', '29');

DROP TABLE IF EXISTS CONTACTS;

CREATE TABLE CONTACTS (
    id INT AUTO_INCREMENT  PRIMARY KEY,
    id_customer INT NOT NULL,
    type INT NOT NULL,
    contact VARCHAR(50)
);